version: 2.1
jobs:
  build:
    environment:
          IMAGE: mmcty/prometheus_bot
    docker:
      - image: docker:19
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/image.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/image.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=$IMAGE -t $IMAGE .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/image.tar $IMAGE
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/image.tar
      - deploy:
          name: Push application Docker image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" \
            --password-stdin
            docker tag $IMAGE "$IMAGE:$CIRCLE_BUILD_NUM"
            docker push "$IMAGE:$CIRCLE_BUILD_NUM"
            docker tag $IMAGE "$IMAGE:latest"
            docker push "$IMAGE:latest"
